name: Publish Docker
on:
  push:
    branches:
      - main
    paths:
      - 'docker/cleanspeak/release-trigger'
concurrency: docker-concurrency-group
jobs:
  multiarch-build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set variabless
        run: |
          echo "CLEANSPEAK_VERSION=$(cat docker/cleanspeak/release-trigger | grep version= | awk -F= {'print $2'})" >> $GITHUB_ENV
          echo "CLEANSPEAK_PRE_RELEASE=$(cat docker/cleanspeak/release-trigger | grep preRelease= | awk -F= {'print $2'})" >> $GITHUB_ENV
          echo "CLEANSPEAK_TAG_SUFFIX=$(cat docker/cleanspeak/release-trigger | grep tagSuffix= | awk -F= {'print $2'})" >> $GITHUB_ENV
      - name: Build version tags
        run: |
          echo "CLEANSPEAK_TAGS=cleanspeak/cleanspeak-app:${{ env.CLEANSPEAK_VERSION }}${{ env.CLEANSPEAK_TAG_SUFFIX }}" >> $GITHUB_ENV
      - name: Optional :latest tag
        if: ${{ env.CLEANSPEAK_PRE_RELEASE == 'false' }}
        run: |
          echo "CLEANSPEAK_TAGS=${{ env.CLEANSPEAK_TAGS }},cleanspeak/cleanspeak-app:latest${{ env.CLEANSPEAK_TAG_SUFFIX }}" >> $GITHUB_ENV
      - name: Job summary
        run: |
          echo "Version: ${{ env.CLEANSPEAK_VERSION }}"
          echo "PreRelease: ${{ env.CLEANSPEAK_PRE_RELEASE }}"
          echo "App Tags: ${{ env.CLEANSPEAK_TAGS }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push cleanspeak-app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/cleanspeak/cleanspeak/Dockerfile
          build-args: CLEANSPEAK_VERSION=${{ env.CLEANSPEAK_VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.CLEANSPEAK_TAGS }}
